### ISSUE TITLE
Comments compressed to half screen and displaying on the same side

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#11]
All the comments are displaying on a single side in screen and automatically arranged to half screen.
See screenshot below:
![screenshot_2017-10-04-22-11-52-270_com deepak informationbank](https://user-images.githubusercontent.com/29884008/31189425-d3f1af0c-a955-11e7-9998-a9bddff0ebfb.png)

**Comment by MajjigaDeepak** [comment]
hi , Can u let me know if this issue is still persists r not...please check. if yes then reopen.
