### ISSUE TITLE
Critical issue: Once a post is liked, the post is getting duplicated one by one for each update( Also the counter is not working for like posts)

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#12]
All the posts are getting duplicated if an update is made. Please check the app home page posts:
See below - same post showing twice:
Also the like counter is not working as expected and not getting updated(counter) - this might be one reason for this issue.
![screenshot_2017-10-04-22-14-36-993_com deepak informationbank](https://user-images.githubusercontent.com/29884008/31189784-d6ec0d28-a956-11e7-822c-f6fdc63c645c.png)

**Comment by MajjigaDeepak** [comment]
This issue resolved..please validate.
