### ISSUE TITLE
While sharing the private group - add additional text before unique id

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#14]
While sharing the private group add text before the unique id as example below:
private group unique id: "here unique id should be displayed"
![screenshot_2017-10-04-22-17-11-864_android](https://user-images.githubusercontent.com/29884008/31190240-2f2889c0-a958-11e7-99fa-5ddbc3f23385.png)

**Comment by MajjigaDeepak** [comment]
hi this issue has fixed. Please validate and let me know any changes is requred.
