### ISSUE TITLE
Change Alert Dialog Popup content

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#2]
As seen below the alert dialog is showing the predefined text as AlertDialog Example- Change it to relevant text.
Change it like: "Currently no cards are tagged under this category. Please check other categories"
![screenshot_2017-07-02-22-54-23-836_com deepak informationbank](https://user-images.githubusercontent.com/29884008/27825986-12714974-60cf-11e7-9ca4-704854ef15bb.png)
![screenshot_2017-07-03-12-14-48-677_com deepak informationbank](https://user-images.githubusercontent.com/29884008/27826008-22780308-60cf-11e7-8de1-32a375b0a92a.png)

**Comment by MajjigaDeepak** [comment]
Fixed the issue.
