### ISSUE TITLE
Like counter is not working as expected

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#4]
Like counter is by default getting selected and when we like and dislike the counter is display as negative(-1) - counter is going negative:
![screenshot_2017-07-03-12-27-02-874_com deepak informationbank](https://user-images.githubusercontent.com/29884008/27830860-e734d50c-60e5-11e7-8387-802e41a32bd7.png)

**Comment by MajjigaDeepak** [comment]
Fixed the issue.
