### ISSUE TITLE
Creator name for all the groups displaying default user name

### ISSUE THREAD

**Issue by sumanthstartit** [MajjigaDeepak/AndroidApp1#5]
Hi Team,
By default, whatever group we select, the creator name under the menu is showing the default user name. Please verify and correct if with actual creator of the group:
![whatsapp image 2017-07-22 at 2 51 23 pm](https://user-images.githubusercontent.com/29884008/28490016-3489d9a4-6eee-11e7-837b-2ad835f56a09.jpeg)

**Comment by MajjigaDeepak** [comment]
issue resolved.
